### ISSUE TITLE
Magic Mirror not show on screen at all after installation of module. 

### ISSUE THREAD

**Issue by cbuys** [Jacopo1891/MMM-GoogleTrafficTimes#4]
The service starts, but there is just the desktop wallpaper on screen. The module config in config.js is below. If I comment out the module config, everything loads up as expected. The Google Cloud Console lists Maps JavaScript API, Geocoding API, and Distance Matrix API under the API key that I am using. I ran the debug command as directed in the README. That is also below. I am not seeing why this is broken. Any help is appreciated.

	{
		module: "MMM-GoogleTrafficTimes",
			position: "top_left",
			config: {
				key: "Copied from Google and the 3 required API are enabled",
				origin: "my street address",
				destinations: [
			        {
			        	name: "work1",
			        	address: "work1 street address",
			        },
			        {
			        	name: "work2",
			        	address: "work2 street address",
			        },
					{
						name: "work3",
						address: "work3 street address",
					}
		        ],
				updateInterval: 900000,
				avoidHighways: false,
				avoidTolls: false,
				mode: "driving",
				language: "en-US",
				offsetTime: 25,
				lastUpdate: true,
				timeLastUpdateWarning: 1,
				debug: true
			}
	},

npm start dev | grep MMM-GoogleTrafficTimes
[01.04.2024 15:26.34.019] [ERROR] (node:22214) UnhandledPromiseRejectionWarning: Error: Cannot find module 'core-js/modules/es.string.replace.js'
Require stack:
- /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/url-signature/dist/index.umd.js
- /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js
- /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/google-maps-services-js/dist/directions.js
- /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/google-maps-services-js/dist/client.js
- /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/google-maps-services-js/dist/geolocate.js
- /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/google-maps-services-js/dist/index.js
- /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_helper.js
- /home/walladmin/MagicMirror/js/app.js
- /home/walladmin/MagicMirror/js/electron.js
- /home/walladmin/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:116646)
    at Module._resolveFilename (/home/walladmin/MagicMirror/node_modules/module-alias/index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at /home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/url-signature/dist/index.umd.js:1:79
    at Object.<anonymous> (/home/walladmin/MagicMirror/modules/MMM-GoogleTrafficTimes/node_modules/@googlemaps/url-signature/dist/index.umd.js:1:807)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
(Use `electron --trace-warnings ...` to show where the warning was created)
[01.04.2024 15:26.34.021] [ERROR] (node:22214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)

**Comment by Jacopo1891** [comment]
Hi! Have you have execute the install command after download?
Once in ~/MagicMirror/modules/MMM-GoogleTrafficTimes run:

`npm install`

**Comment by cbuys** [comment]
Absolutely.

**Comment by Jacopo1891** [comment]
Ok... Try to execute:
`npm install core-js`

**Comment by cbuys** [comment]
Amazing. That fixed it! you rock.
